language: ruby
install:
  - gem uninstall bundler
  - gem install bundler --version '1.7.4'
script: "rake"

sudo: required
services:
  - docker

before_install:
  - docker build -t reactapp -f Dockerfile.dev .

scripts:
  - docker run reactapp npm run test -- --coverage
