language: bash

sudo: required

services:
  - docker

before_install:
  - gem install bundler --pre
  - docker build -t reactapp -f Dockerfile.dev .

scripts:
  - docker run reactapp npm run test -- --coverage
